### PR TITLE
Revert "Added PSR-6 to Illuminate adapter (#140)"

### PR DESCRIPTION
**Pull request by chalasr**
This change breaks the symfony test suite on PHP 5.5:
https://ci.appveyor.com/project/fabpot/symfony/build/1.0.19631
https://travis-ci.org/symfony/symfony/jobs/210480963

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
:+1:
this is making SF tests red

**Comment by Nyholm** [comment]
Thank you @chalasr. 

I reverted the change on this library. I had to send a PR to php-cache/cache.

**Comment by chalasr** [comment]
Green again. You rock :)

**Comment by Nyholm** [comment]
This will not happen again. I just tagged 1.0.0. 

https://github.com/php-cache/tag-interop/releases/tag/1.0.0

**Pull request closed without merging**
